// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "product-service",
    "version": "1"
  },
  "paths": {
    "/products/{id}": {
      "get": {
        "summary": "getProductById",
        "description": "",
        "operationId": "getProductById.get.products/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "successful API Response",
            "schema": {
              "$ref": "#/definitions/Product"
            }
          }
        }
      }
    },
    "/products": {
      "get": {
        "summary": "getProductList",
        "description": "",
        "operationId": "getProductList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "successful API Response",
            "schema": {
              "$ref": "#/definitions/Products"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Product": {
      "properties": {
        "id": {
          "title": "Product.id",
          "type": "string"
        },
        "title": {
          "title": "Product.title",
          "type": "string"
        },
        "price": {
          "title": "Product.price",
          "type": "number"
        },
        "description": {
          "title": "Product.description",
          "type": "string"
        },
        "category": {
          "title": "Product.category",
          "type": "string"
        },
        "image": {
          "title": "Product.image",
          "type": "string"
        },
        "rating": {
          "$ref": "#/definitions/Rating",
          "title": "Product.rating"
        }
      },
      "required": [
        "id",
        "title",
        "price",
        "description",
        "category",
        "image",
        "rating"
      ],
      "additionalProperties": false,
      "title": "Product",
      "type": "object"
    },
    "Products": {
      "items": {
        "$ref": "#/definitions/Product",
        "title": "Products.[]"
      },
      "title": "Products.[]",
      "type": "array"
    },
    "Rating": {
      "properties": {
        "rate": {
          "title": "Rating.rate",
          "type": "number"
        },
        "count": {
          "title": "Rating.count",
          "type": "number"
        }
      },
      "required": [
        "rate",
        "count"
      ],
      "additionalProperties": false,
      "title": "Rating",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};