// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "import-service-viktoryia-yalavaya",
    "version": "1"
  },
  "paths": {
    "/import": {
      "get": {
        "summary": "importProductsFile",
        "description": "",
        "operationId": "importProductsFile.get.import",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "successful API Response",
            "schema": {
              "$ref": "#/definitions/Products"
            }
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};